export const TOGGLE_HEADER = 'TOGGLE_HEADER';
export const FETCH_POST_LIST = 'FETCH_POST_LIST';
export const FETCH_POST_VIEW = 'FETCH_POST_VIEW';
export const FETCH_ARCHIVE_LIST = 'FETCH_ARCHIVE_LIST';
export const FETCH_CATEGORIES_LIST = 'FETCH_CATEGORIES_LIST';